export interface Theme {
  bgPrimary: string;
  bgSecondary: string;
  bgTertiary: string;
  bgQuaternary: string;
  bgConstruction: string;
  bgConstructionHeader: string;
  bgError: string;
  bgSuccess: string;
  bgWarning: string;
  bgPrimaryLight: string;
  bgOverlay: string;
  borderPrimary: string;
  borderSecondary: string;
  borderTertiary: string;
  textPrimary: string;
  textSecondary: string;
  textTertiary: string;
  textPlaceholder: string;
  accent: string;
  accentLight: string;
  accentHover: string;
  error: string;
  errorDeep: string;
  success: string;
  successDeep: string;
  warning: string;
  formulaBlue: string;
  selectBg: string;
  inputBorder: string;
  dropdownBg: string;
  dropdownHover: string;
  btnPrimaryBg: string;
  btnPrimaryText: string;
  btnOutlineBg: string;
  btnOutlineBorder: string;
  btnOutlineText: string;
  tabActiveBorder: string;
  shadowDropdown: string;
  shadowModal: string;
  badgeBorder: string;
  badgeNoValueBorder: string;
  badgeNoValueBg: string;
  badgeNoValueText: string;
  inputFocusBorder: string;
}

export const lightTheme: Theme = {
  bgPrimary: '#fff',
  bgSecondary: '#fafafa',
  bgTertiary: '#f5f5f5',
  bgQuaternary: '#f0f0f0',
  bgConstruction: '#f5f9ff',
  bgConstructionHeader: '#e3f2fd',
  bgError: '#ffebee',
  bgSuccess: '#e8f5e9',
  bgWarning: '#fff3e0',
  bgPrimaryLight: '#e3f2fd',
  bgOverlay: 'rgba(0,0,0,0.1)',
  borderPrimary: '#ddd',
  borderSecondary: '#eee',
  borderTertiary: '#e0e0e0',
  textPrimary: '#333',
  textSecondary: '#666',
  textTertiary: '#888',
  textPlaceholder: '#999',
  accent: '#1976d2',
  accentLight: '#bbdefb',
  accentHover: '#1565c0',
  error: '#c62828',
  errorDeep: '#d32f2f',
  success: '#2e7d32',
  successDeep: '#66bb6a',
  warning: '#e65100',
  formulaBlue: '#1565c0',
  selectBg: '#fff',
  inputBorder: '#d9d9d9',
  dropdownBg: '#fff',
  dropdownHover: '#f5f5f5',
  btnPrimaryBg: '#1976d2',
  btnPrimaryText: '#fff',
  btnOutlineBg: '#fff',
  btnOutlineBorder: '#1976d2',
  btnOutlineText: '#1976d2',
  tabActiveBorder: '#1976d2',
  shadowDropdown: '0 2px 8px rgba(0,0,0,0.1)',
  shadowModal: '0 4px 20px rgba(0,0,0,0.2)',
  badgeBorder: '#bbdefb',
  badgeNoValueBorder: '#e0e0e0',
  badgeNoValueBg: '#f5f5f5',
  badgeNoValueText: '#999',
  inputFocusBorder: '#1976d2',
};

export const darkTheme: Theme = {
  bgPrimary: '#151515',
  bgSecondary: '#0f0f0f',
  bgTertiary: '#1e1e1e',
  bgQuaternary: '#2c2c2c',
  bgConstruction: '#1a2332',
  bgConstructionHeader: '#1e2d40',
  bgError: '#2d1518',
  bgSuccess: '#1a2e1c',
  bgWarning: '#2d2215',
  bgPrimaryLight: '#1a2740',
  bgOverlay: 'rgba(0,0,0,0.5)',
  borderPrimary: '#3d3d3d',
  borderSecondary: '#2c2c2c',
  borderTertiary: '#333',
  textPrimary: '#e0e0e0',
  textSecondary: '#a0a0a0',
  textTertiary: '#787878',
  textPlaceholder: '#666',
  accent: '#426eff',
  accentLight: '#2a3d66',
  accentHover: '#5c8aff',
  error: '#ef5350',
  errorDeep: '#f44336',
  success: '#66bb6a',
  successDeep: '#81c784',
  warning: '#ffa726',
  formulaBlue: '#5c94d6',
  selectBg: '#1e1e1e',
  inputBorder: '#555',
  dropdownBg: '#1e1e1e',
  dropdownHover: '#2c2c2c',
  btnPrimaryBg: '#426eff',
  btnPrimaryText: '#fff',
  btnOutlineBg: '#1e1e1e',
  btnOutlineBorder: '#426eff',
  btnOutlineText: '#426eff',
  tabActiveBorder: '#426eff',
  shadowDropdown: '0 2px 8px rgba(0,0,0,0.4)',
  shadowModal: '0 4px 20px rgba(0,0,0,0.5)',
  badgeBorder: '#2a3d66',
  badgeNoValueBorder: '#3d3d3d',
  badgeNoValueBg: '#2c2c2c',
  badgeNoValueText: '#787878',
  inputFocusBorder: '#426eff',
};
